-- 1. Show each customer's FirstName, LastName, and the name of the employee who supports them (SupportRepId → Employee).
SELECT c.FirstName AS First_Name, c.LastName AS Last_Name, e.FirstName AS employee_name
From Customer c
JOIN Employee  e
ON c.SupportRepId = e.EmployeeId;
-- 2. Show all invoices with the customer's first and last name attached.
Select c.FirstName AS FirstName, c.LastName AS Last_Name, i.total AS all_invoices
FROM Customer c
JOIN Invoice i
ON c.CustomerId = i.CustomerId;
-- 3. Show every track's Name along with its Album Title and Artist Name (3-table join).
SELECT t.Name AS track_name, a.Title AS album_title, art.Name AS artist_name
FROM Track t
JOIN Album a
ON t.AlbumId = a.AlbumId
JOIN Artist art
ON art.ArtistId = a.ArtistId;
-- 4. Show each track's Name and its Genre Name. Include tracks even if they don't have a genre assigned (hint: LEFT JOIN direction matters).
SELECT t.Name AS track_name, g.Name as genre_name
FROM Track t
LEFT JOIN Genre g
ON t.GenreId = g.GenreId;
-- 5. List all employees and the count of customers they support. Include employees with zero customers.
SELECT e.FirstName AS employee_name,  COUNT(c.CustomerId) AS customers_support
FROM Employee e
LEFT JOIN Customer c
on e.EmployeeId= c.SupportRepId
GROUP BY e.EmployeeId;
-- 6. Show the total revenue (sum of invoice totals) generated by each employee through their supported customers.
SELECT SUM(i.total) AS total_revenue, e.FirstName AS employee_name
FROM Employee e
JOIN Customer c
ON c.SupportRepId = e.EmployeeId
JOIN invoice i
ON c.CustomerId = i.CustomerId
GROUP BY e.EmployeeId;

-- 7. For each genre, show the genre name and the total number of tracks in that genre. Sort by track count descending.
SELECT g.Name AS genre_name, COUNT(t.TrackId) AS track_count
FROM Genre g
LEFT JOIN Track t
    ON t.GenreId = g.GenreId
GROUP BY g.GenreId
ORDER BY track_count DESC;
-- 8. Find the top 10 customers by lifetime spend. Show FirstName, LastName, Country, and total spent.
SELECT c.FirstName AS First_Name, c.LastName AS Last_Name, c.Country AS Country, SUM(i.total) AS lifetime_spent
FROM Customer c
LEFT JOIN Invoice i
ON i.Customerid = c.CustomerId
GROUP BY c.CustomerId
ORDER BY SUM(i.total) DESC
LIMIT 10;
-- 9. Show every artist and the number of albums they have. Include artists with zero albums.
SELECT art.Name AS artist_Name, COUNT(a.Title) AS album_count
FROM Artist art
LEFT JOIN Album a
ON art.ArtistId = a.ArtistId
GROUP BY art.ArtistId;
-- 10. For each playlist, show the PlaylistId, Name, and the number of tracks on it.
SELECT p.PlaylistId AS playlist_id, p.Name AS playlist_name, COUNT(pt.Trackid) AS track_count
FROM Playlist p
LEFT JOIN PlaylistTrack pt
ON p.PlaylistId = pt.PlaylistId
GROUP BY p.PlaylistId;
-- 11. Find the top 5 best-selling tracks of all time. Show TrackId, Track Name, Artist Name, and total quantity sold (from InvoiceLine).
SELECT t.trackid AS track_id, t.Name AS track_name, art.Name AS artist_Name, SUM(il.Quantity) AS total_quantity_sold
FROM Track t
JOIN Album a
ON t.AlbumId = a.AlbumId
JOIN Artist art
ON a.ArtistId = art.ArtistId
JOIN InvoiceLine il
ON il.TrackId = t.TrackId
GROUP BY t.TrackId
ORDER BY SUM(il.Quantity) DESC
LIMIT 5;
-- 12. Show each country's total revenue AND the number of unique customers who purchased there. Sort by revenue descending.
SELECT c.Country AS country_name, SUM(i.total) AS total_revenue, COUNT(DISTINCT c.CustomerId) AS unique_customers
FROM Customer c
JOIN invoice i
ON i.Customerid = C.CustomerId
GROUP BY c.Country
ORDER BY SUM(i.total) DESC;